### PR TITLE
Added support for changing DLL list order

### PR DESCRIPTION
**Pull request by alessandromrc**
I'm not a design expert or anything so this change might look really bad on everybody else's eyes but I do care about the functionality as I'm frequently changing injection order and this will allow to do so.

Here's a picture of how it looks:
image

### CODE REVIEW

**Comment by Sainan** [comment]
How is the injection order at all relevant?

**Comment by alessandromrc** [comment]
Because I inject stuff like renderers that need a specific order as the dll loaded next will need to call the one before I've injected (this is just the way I'm coding my own stuff but I'm sure it might be useful to have this feature anyway)

**Comment by Sainan** [comment]
Sounds like the way you coded your stuff is a bit suboptimal. Not to say this feature is entirely worthless, but probably more work to do proper than it's worth.

**Comment by alessandromrc** [comment]
If I could have done different I would have but sadly as somebody started to stop loading dlls from the executable folder I need to do this trickery to bypass all this.

**Pull request closed without merging**
