### PR TITLE
Add Dark Mode to Changelog

### PR DESCRIPTION
**Pull request by alessandromrc**
Hi, I've added Dark Mode to the Changelog page too to keep the same style through the entire launcher.
Here's a picture of the actual result:

image

### CODE REVIEW

**Comment by Sainan** [comment]
You appear to have changed the indentation, making the diff unusable.

**Comment by alessandromrc** [comment]
Will fix that now

**Comment by Sainan** [comment]
Also, idk why you would inject JS just to modify the CSS, but I've deployed your styling rules to https://stand.gg/help/changelog-launchpad, so that's not needed anymore. 🙂

**Comment by alessandromrc** [comment]
Well @Sainan at this point I can close the pr and keep it directly the modified css in the webpage but there's still the issue with the tilebar anyway which needs to be in dark mode too

**Comment by alessandromrc** [comment]
@Sainan I've noticed a small issue on the changelog page when seen on a web browser now:

image

Seems like you forgot to override the html background too

**Comment by Sainan** [comment]
I just copied your JS into CSS form. 😉 

Besides, it doesn't have to work in a _normal_ browser; it has to work in the godforsaken IE 9 or whatever that this webframe is using.

**Pull request closed without merging**
